import { Header, StatsCard, TripCard } from "../../../components";
import { getAllUsers, getUser } from "~/appwrite/auth";
import type { Route } from './+types/dashboard';
import { getTripsByTravelStyle, getUserGrowthPerDay, getUsersAndTripsStats } from "~/appwrite/dashboard";
import { getAllTrips } from "~/appwrite/trips";
import { parseTripData } from "~/lib/utils";
import {
    Category,
    ChartComponent,
    ColumnSeries,
    DataLabel, SeriesCollectionDirective, SeriesDirective,
    SplineAreaSeries,
    Tooltip,
    Inject
} from "@syncfusion/ej2-react-charts";
import { ColumnDirective, ColumnsDirective, GridComponent } from "@syncfusion/ej2-react-grids";
import { tripXAxis, tripyAxis, userXAxis, useryAxis } from "~/constants";

export const clientLoader = async () => {
    const [
        user,
        dashboardStats,
        trips,
        userGrowth,
        tripsByTravelStyle,
        allUsers,
    ] = await Promise.all([
        getUser(),
        getUsersAndTripsStats(),
        getAllTrips(4, 0),
        getUserGrowthPerDay(),
        getTripsByTravelStyle(),
        getAllUsers(0,4),
    ])

    const allTrips = (trips?.allTrips || []).map(({ $id, tripDetail, imageUrls }: any) => {
        const parsed = parseTripData(tripDetail);
        return {
            id: $id,
            ...parsed,
            imageUrls: imageUrls ?? []
        }
    })

    const mappedUsers = (allUsers?.users || []).map((user: any) => ({
        imageUrl: user.imageUrl,
        name: user.name,
        count: user.itineraryCount ?? Math.floor(Math.random() * 10),
    }))

    return {
        user,
        dashboardStats,
        allTrips,
        userGrowth,
        tripsByTravelStyle,
        allUsers: mappedUsers
    }
}

const Dashboard = ({ loaderData }: Route.ComponentProps) => {
    const { user, dashboardStats, allTrips, userGrowth, tripsByTravelStyle, allUsers } = loaderData;

    const tripsForGrid = allTrips.map((trip: any) => ({
        imageUrl: trip.imageUrls[0] || '/assets/images/placeholder.png',
        name: trip.name || 'Untitled Trip',
        interest: typeof trip.interests === 'string' ? trip.interests : trip.interests?.[0] || 'General',
    }))

    const usersAndTrips = [
        {
            title: 'Latest User Signups',
            dataSource: allUsers,
            field: 'count',
            headerText: 'Trips created'
        },
        {
            title: 'Trips by Interest',
            dataSource: tripsForGrid,
            field: 'interest',
            headerText: 'Interests'
        }
    ]

    return (
        <main className="dashboard pt-32 pb-20 bg-[#FAFBFC]">
            <div className="max-w-7xl mx-auto px-6 lg:px-10">
                {/* Header Section aligned with TripDetail Typography */}
                <Header
                    title={`Welcome back, ${user?.name ?? 'Guest'} 👋`}
                    description="Monitor your travel ecosystem, track growth, and explore the latest AI-generated itineraries."
                />

                {/* Stats Cards Section */}
                <section className="mt-12">
                    <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
                        <StatsCard
                            headerTitle="Total Explorers"
                            total={dashboardStats.totalUsers}
                            currentMonthCount={dashboardStats.usersJoined.currentMonth}
                            lastMonthCount={dashboardStats.usersJoined.lastMonth}
                        />
                        <StatsCard
                            headerTitle="Generated Trips"
                            total={dashboardStats.totalTrips}
                            currentMonthCount={dashboardStats.tripsCreated.currentMonth}
                            lastMonthCount={dashboardStats.tripsCreated.lastMonth}
                        />
                        <StatsCard
                            headerTitle="Active Sessions"
                            total={dashboardStats.userRole.total}
                            currentMonthCount={dashboardStats.userRole.currentMonth}
                            lastMonthCount={dashboardStats.userRole.lastMonth}
                        />
                    </div>
                </section>

                {/* Created Trips Section - Matching the Gallery/Grid style */}
                <section className="mt-20">
                    <div className="flex justify-between items-end mb-8">
                        <div>
                            <h2 className="text-3xl font-bold text-slate-900">Recently Created</h2>
                            <p className="text-slate-500 mt-1">The latest travel plans generated by users.</p>
                        </div>
                    </div>

                    <div className='grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-6'>
                        {allTrips.map((trip: any) => (
                            <TripCard
                                key={trip.id}
                                id={trip.id}
                                name={trip.name || 'AI Trip'}
                                imageUrl={trip.imageUrls[0]}
                                location={trip.itinerary?.[0]?.location || trip.country || 'Global'}
                                tags={[
                                    typeof trip.interests === 'string' ? trip.interests : trip.interests?.[0],
                                    trip.travelStyle
                                ].filter(Boolean)}
                                price={trip.estimatedPrice || 'Contact'}
                            />
                        ))}
                    </div>
                </section>

                {/* Analytics Section - Refined Chart Containers */}
                <section className="grid grid-cols-1 lg:grid-cols-2 gap-10 mt-20">
                    <div className="bg-white p-8 rounded-[32px] shadow-sm border border-slate-100">
                        <h3 className="text-xl font-bold text-slate-900 mb-6 px-2">Growth Analytics</h3>
                        <ChartComponent
                            id="chart-1"
                            primaryXAxis={userXAxis}
                            primaryYAxis={useryAxis}
                            chartArea={{ border: { width: 0 } }}
                            tooltip={{ enable: true }}
                            background="transparent"
                        >
                            <Inject services={[ColumnSeries, SplineAreaSeries, Category, DataLabel, Tooltip]} />
                            <SeriesCollectionDirective>
                                <SeriesDirective
                                    dataSource={userGrowth}
                                    xName="day"
                                    yName="count"
                                    type="Column"
                                    columnWidth={0.3}
                                    fill="#3B82F6"
                                    cornerRadius={{ topLeft: 6, topRight: 6 }}
                                />
                                <SeriesDirective
                                    dataSource={userGrowth}
                                    xName="day"
                                    yName="count"
                                    type="SplineArea"
                                    fill="rgba(59, 130, 246, 0.1)"
                                    border={{ width: 2, color: '#3B82F6' }}
                                />
                            </SeriesCollectionDirective>
                        </ChartComponent>
                    </div>

                    <div className="bg-white p-8 rounded-[32px] shadow-sm border border-slate-100">
                        <h3 className="text-xl font-bold text-slate-900 mb-6 px-2">Travel Style Trends</h3>
                        <ChartComponent
                            id="chart-2"
                            primaryXAxis={tripXAxis}
                            primaryYAxis={tripyAxis}
                            chartArea={{ border: { width: 0 } }}
                            tooltip={{ enable: true }}
                            background="transparent"
                        >
                            <Inject services={[ColumnSeries, Category, DataLabel, Tooltip]} />
                            <SeriesCollectionDirective>
                                <SeriesDirective
                                    dataSource={tripsByTravelStyle}
                                    xName="travelStyle"
                                    yName="count"
                                    type="Column"
                                    fill="#8B5CF6"
                                    columnWidth={0.4}
                                    cornerRadius={{ topLeft: 6, topRight: 6 }}
                                />
                            </SeriesCollectionDirective>
                        </ChartComponent>
                    </div>
                </section>

                {/* Table/Grid Section - Softened Grid Style */}
                <section className="grid grid-cols-1 lg:grid-cols-2 gap-10 mt-10">
                    {usersAndTrips.map(({ title, dataSource, field, headerText }, i) => (
                        <div key={i} className="flex flex-col gap-6 bg-white p-8 rounded-[32px] shadow-sm border border-slate-100">
                            <h3 className="text-xl font-bold text-slate-900">{title}</h3>
                            <GridComponent
                                dataSource={dataSource}
                                gridLines="None"
                                rowHeight={60}
                            >
                                <ColumnsDirective>
                                    <ColumnDirective
                                        field="name"
                                        headerText="Name"
                                        width="200"
                                        textAlign="Left"
                                        template={(props: any) => (
                                            <div className="flex items-center gap-3">
                                                <img src={props.imageUrl} alt="img" className="rounded-full size-10 object-cover shadow-sm" />
                                                <span className="text-slate-900 font-semibold">{props.name}</span>
                                            </div>
                                        )}
                                    />
                                    <ColumnDirective
                                        field={field}
                                        headerText={headerText}
                                        width="150"
                                        textAlign="Left"
                                        template={(props: any) => (
                                            <span className="text-slate-500 font-medium">{props[field]}</span>
                                        )}
                                    />
                                </ColumnsDirective>
                            </GridComponent>
                        </div>
                    ))}
                </section>
            </div>
        </main>
    )
}

export default Dashboard;